services:
  elasticsearch:
    image: elasticsearch:8.16.1
    networks:
      - elastic
  
  logstash:
    image: logstash:8.16.1
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  kibana:
    image: kibana:8.16.1
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
   